### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by FZambia** [gazarovv/park-python-football-team7#1]
[line 114](https://github.com/gazarovv/park-python-football-team7/blob/master/main.py#L114) - поиск игры лучше было бы делать с помощью словаря, а не итерироваться, но в контексте данной задачи - сойдет.

Магические числа в коде - 6 и 14 - программист, читающий ваш код должен понимать, что он означает - поэтому лучше для таких вещей использовать константы/переменные c говорящим названием. Сейчас, просто изменив кол-во команд, нужно менять код еще в нескольких местах.

Код - смесь русского и английского языков, желательно называть переменные в одном стиле и английский предпочтительнее.

По функционалу нет вопросов - все так, как нужно.

**Comment by gazarovv** [comment]
Исправили все, но не смогли понять как сделать с помощью словаря.

**Comment by FZambia** [comment]
Отлично, спасибо! Вот [мое решение](https://gist.github.com/FZambia/e1dd1b36766e12564739b179c3460ca1) - там как раз результат из словаря достается.
